### ISSUE TITLE
occasionally unintended string added to job.payload

### ISSUE THREAD

**Issue by kirrie** [veny/GearmaNode#22]
Hi.

This seem like occuring when job is queued before worker run. But not all cases.
In that situation, I get a weird string in job.payload like below.

"...... (job.payload) ... RES\nRES\n"

**Comment by veny** [comment]
hi Kirrie,

unfortunately I cannot figure out the problem, but I can provide you some tips to find the problem.

1) start the gearman job server in debug mode (it will produce a lot of output)
```
gearmand --verbose=DEBUG
```
in case your problem occurs check log of the worker. you should see something as follows
```
verbose: packet parsed, bytes=44, type=JOB_ASSIGN
```
* number of bytes will be different in your case, but JOB_ASSIGN is important
* then check output of gearman job server, search for following
```
DEBUG 2015-01-04 20:35:49.557159 [     3 ] send() 44 bytes to peer -> libgearman-server/io.cc:403
DEBUG 2015-01-04 20:35:49.557166 [     3 ] Sent JOB_ASSIGN -> libgearman-server/thread.cc:356
 ```
if the number bytes matchs (44 in this case), then the unintended string added to job.payload was sent by job server, which means it was sent from client side, which means there is probably problem on client side.

2) additionally add following code to 'job-server.js' on line 362:
```
if (packetType === protocol.PACKET_TYPES.JOB_ASSIGN) {
     console.log('BF#22 >>> ' + parsedPacket[3])
}
```
this displays the payloiad immediately after parsing the socket communication, so you can see on low level if the socket already contained wrong data.

regards,
veny

**Comment by veny** [comment]
closed because of inactivity
