### ISSUE TITLE
How can I set winston logger for gearmanode?

### ISSUE THREAD

**Issue by mike442144** [veny/GearmaNode#32]
Since I have my own winston logger and I want put this together with gearmanode. But when I do like this:

    winston.loggers.add('Client', {
    console: {
    colorize: true,
    level:'info'
    },
    file: {
	filename: '../log/gearman.client.log'
    }})

I use code above because I see the code in `Client.js` get logger use `Client` but it didn't work, all verbose information will be printed in the console and when I set like this:
    
    `gearman.Client.logger.transports.console.level = 'info';`

It works. Why?

**Comment by veny** [comment]
the reason is that gearmanode library registers more loggers. I updated the documentation to list all the loggers. you can configure all of them before first use of gearmanode like this:

```javascript
var winston = require('winston');
winston.loggers.default = {
    transports: [
      new winston.transports.Console({
        level: 'info',
        colorize: true
      })
    ]
  };
```

for more info about winston see the library itself.

**Comment by mike442144** [comment]
Thanks for your reply, But I think `gearman.Client.logger` is equal to `winston.loggers.get("Client")` so `gearman.Client.logger.transports.console.level = 'info';` is equal to `winston.loggers.get("Client").transports.console.level='info'` which I referred in `winston.loggers.add` function.

**Comment by mike442144** [comment]
Also

winston.loggers.default = {
    transports:[
	new logger.transports.Console({
	    level:'info',
	    colorize:true
	}),
	new logger.transports.File({
	    filename:'../../log/gearman.client.log',
	    level:'warn',
	    logstash:true
	})
    ]
}

doesn't work.

**Comment by mike442144** [comment]
I read winston source code in detail, I find when your code winston.loggers.get("Client") means that winston will create a new instance of winston.Logger which will use Container's default options that as following:
    this.default = {
        transports: [
          new winston.transports.Console({
            level: 'silly',
            colorize: false
          })
        ]
      }
and at the beginning of my script file ,I first require `gearmanode` then modify `winston.loggers.default`. It made no sense. So when I reverse them, working well. So I can modify `winston.loggers.default` before 'gearmanode' required, but I still cannot find the reason for this https://github.com/veny/GearmaNode/issues/32#issuecomment-112261093

**Comment by veny** [comment]
sorry mike,
I do believe this is a question for Winston forum. I just obtain my loggers by calling the Winston's API.

a tip: as far I know, you can configure a logger with options only by first call of `winston.loggers.get()`. thereafter if a logger with given ID already exist, you obtain already existing object.

**Comment by mike442144** [comment]
Thanks, I'll continue reading code before I can solve

**Comment by mike442144** [comment]
It's hard to use logger, when I wanna run the client and worker in background but the console is continuing printing information. I want to write all log to file. But how can I do that?

**Comment by veny** [comment]
there is many options, at least:
* you can redirect the standard output in console
* you can use the approach I suggested above
* you can initialize your own Logger and replace the GearmaNode default one
* you can read Winston source code to find other solution
* you can ask in Winston forum

**Comment by mike442144** [comment]
Thank you, the first solution is useless, when I run like node `xxx.client.js` > xxx.log, the program also printed msg in console. Finally I use code as below:

    if(env === 'production'){
        logClient.remove(logClient.transports.console)
        logWorker.remove(logWorker.transports.console)
        logServer.remove(logServer.transports.console)
        logJob.remove(logJob.transports.console)
        logLB.remove(logLB.transports.console)
        logProtocol.remove(logProtocol.transports.console)
    }

I solved this problem at present, but I hope there will be some easier way to do.
