### ISSUE TITLE
What does background job actually mean?

### ISSUE THREAD

**Issue by mike442144** [veny/GearmaNode#33]
I'm confused with the background job when I search on the `gearman.org` I find manual `http://gearman.org/manual/clients/` but it said nothing about the background job which mentioned on the home page ` background for asynchronous processing`.

Anyone knows the details? Thanks first.

**Comment by veny** [comment]
there is a description:
http://gearman.org/examples/

**Comment by mike442144** [comment]
So it means job should be processed one by one on service side? because to nodejs every job will send to server at the same time, won't be blocked.

**Comment by mike442144** [comment]
Now comes another problem, everything is working well if I call `submitJob` without `options` but worker print these messages if I call with background=true:

    debug: packet encoded, type=WORK_COMPLETE, buffer.size=10522
    verbose: packet sent, type=WORK_COMPLETE, len=10522
    debug: packet encoded, type=PRE_SLEEP, buffer.size=12
    verbose: packet sent, type=PRE_SLEEP, len=12

and then nothing happen even in client side:

    debug: no more a job waiting 4 state JOB_CREATED
    debug: response for client: type=JOB_CREATED, uid=192.168.98.116:4730#H:bda-server:19737

why?

**Comment by veny** [comment]
hi mike,
please read following documentation first: http://gearman.org/protocol/
it provides very good description how the gearman works with some examples on protocol level.

**Comment by mike442144** [comment]
Thanks a lot, I have read it. That's also cannot explain the problem mentioned above. Once I set `background` to `false` everything is ok.

**Comment by veny** [comment]
yes, it explains the problem.
if you use background job, the client sends the payload to gearman server and does NOT wait for a response. so you can only use function `job.workComplete()` (without data) to mark the job done on gearman server. you can NOT send some data to client back.

**Comment by mike442144** [comment]
@veny I see, thanks a lot.

**Comment by ankurhora** [comment]
Hi,
i created the client in node and worker in php... running job in background works fine on the client side 

debug: packet encoded, type=SUBMIT_JOB_BG, buffer.size=340
debug: unconnected job server, uid=localhost:4730
warn: unhandled event, name=lookup
debug: job submited, name=resize, unique=undefined
debug: connection established, uid=localhost:4730
debug: no more a job waiting 4 state JOB_CREATED
--- Job#created - Job(uuid=f1ff6833-44d6-47ec-8948-60a6aa3d2c35, handle=H:xyz:10, server=localhost:4730)

and then processes the rest script but i dont get any thing in my worker. It doesnot output anything 

$worker= new GearmanWorker();
$worker->addServer();
$worker->addFunction("resize", "resize_function");
while ($worker->work());

function resize_function($job)

{
    $workLoad = $job->workload();
    // do stuff
}



This works fine when i submit a job in background.
P.S using gearman in php ( both client & worker) works fine .
