### ISSUE TITLE
Is there a hook for function?

### ISSUE THREAD

**Issue by mike442144** [veny/GearmaNode#34]
Is there a hook for registered on worker, because I wanna handle the `payload` in every registered function, like:

    try{
        JSON.parse(job.payload.toString())
    }catch(err){
        logger.error(err)
    }

If not , I have to write the code in every registered function.

**Comment by veny** [comment]
what about following trick:

```javascript
var before = function (before, fn) {
  return function () {
    arguments[0].payload = before.apply(this, arguments);
    return fn.apply(this, arguments);
  }
}

var jsonParse = function (job) {
    return JSON.parse(job.payload.toString();
};
```

and then:

```javascript
worker.addFunction('reverse', before(jsonParse, function (job) {
    console.log("payload>>> " + job.payload);
    var rslt = job.payload.toString().split("").reverse().join("");
    job.workComplete(rslt);
}));
```

**Comment by mike442144** [comment]
Thanks a lot , that's a kind of solution, but if there is a hook would be better. I think a framework should expose every processing stage to callers.

**Comment by veny** [comment]
please feel free to make a branche and corresponding pull request.

**Comment by veny** [comment]
closed because of inactivity
