### ISSUE TITLE
What dose master do if the worker report error ?

### ISSUE THREAD

**Issue by mike442144** [veny/GearmaNode#36]
As the title mentioned I'm wondering what the master will do if the worker report error or exception. The master will send the job to another worker or just do nothing?

**Comment by veny** [comment]
hi mike,
I do not want to be impolite, but your question is answered in gearman protocol description. please read it, maybe twice, before you ask: http://gearman.org/protocol/
my binding library is practicaly 1:1 javaScript implementation of the protocol, there is only a low abstraction. so if you understand the protocol, you understand my library.

additionally this question shoul be asked in gearman forum.
