### ISSUE TITLE
Limit job response size

### ISSUE THREAD

**Issue by dcolens** [veny/GearmaNode#39]
It would be nice to allow a limit to the size of a job response a bit like bodyparser allows to limit POST sizes. Today a worker could return many gigs of data without any way for the client to stop it.

**Comment by PrintNode-Pete** [comment]
The gearman protocol doesn't allow support this. Should the gearman server want to send you a lot of bytes in a response you've got to accept them and drain the client->server socket before you'll get anything else from the server.

It's not a HTTP 1.x style system where you have multiple sockets for each request and can just terminate one if it doesn't meet a spec and others will remain unaffected. All communication is 'muliplexed' down a single socket.

**Comment by veny** [comment]
thx #PrintNode-Pete for proxying me, your answer is 100% correct,
