### ISSUE TITLE
Job payload with JSON

### ISSUE THREAD

**Issue by defra91** [veny/GearmaNode#46]
I am building a simple gearman architecture to run asynchronous jobs. I want to achieve the following:

- The client submit a job
- The payload of the job is a JSON object or array
- The worker receives the job with the JSON and executed a function

I have an issue, because what the worker receives as payload is a Buffer and I could not find a way to translate it to the original JSON. 

The solution I adopted for now consists of sending the stringified JSON and then parse it with the worker.  It is a working solution but I would rather prefer to skip the stringification and the parsing of the JSON.

Can you please tell me if there is a better way of doing these steps and if in the future you are planning of adding support for JSON translation?

**Comment by veny** [comment]
I would suggest a JSON serialization into a binary format and storing into Buffer. maybe this could be a tool for you: https://github.com/erossignon/serialijse

**Comment by defra91** [comment]
Thank you. That is a better solution which worked for me.
