### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by herlon214** [veny/GearmaNode#51]
Hi guys, after sometime my worker is showing this error:

```
error: socket error: Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
```

Any idea?

**Comment by mike442144** [comment]
Maybe your server is down.

**Comment by herlon214** [comment]
I don't know why but this only occurs on Windows, Linux stay stable always.

**Comment by veny** [comment]
please write a deterministic scenario/test how to simulate it, there is not enough informations in your post

**Comment by herlon214** [comment]
I don't use Gearmanode on windows anymore. On ubuntu server it's working fine.

**Comment by veny** [comment]
ok, thx for info
