### ISSUE TITLE
workComplete not return data when use async mode

### ISSUE THREAD

**Issue by zain-creation** [veny/GearmaNode#56]
Hi Men,
i use client job with background equals true to use async mode, but when i fire workComplete on worker with data inside the complete event in client job dont fire, how can i use async mode with gearman this is my example:
worker ---

`var gearmanode = require('gearmanode');
var worker = gearmanode.worker();

// Background Job
worker.setWorkerId('tjs82dd67d')
worker.addFunction('sleep', function (job) {
    var seconds = new Number(job.payload);
    var cnt = 0;
    var tmo = function() {
        if (cnt < seconds) {
            cnt ++;
            console.log('== sleep: idx=' + cnt + ', ' + job.toString());
            job.reportStatus(cnt, seconds);
            setTimeout(tmo, 1000);
        } else {
            job.workComplete('job completed');
        }
    }
    tmo();
});`

Client ------ 

`var gearmanode = require('gearmanode');
var util = require('util');
var client = gearmanode.client();

// Background Job asking for status
var timeout = 3000;
var client = gearmanode.client();
var job = client.submitJob('sleep', '5', {background: true,unique:'tjs82djjd9'});
job.on('created', function() {
    console.log('--- Job#created - ' + job.toString());
    console.log('--- waiting for wake-up ' + timeout + '[ms] ...')
    setInterval((function() {
        job.getStatus(function(err){console.log('=========== ' + err)});
    }), 1000);
});
job.on('status', function(result) {
    console.log('--- result: ' + util.inspect(result));
    //client.close();
});

job.on('complete', function() {

    console.log('RESULT >>> ' + job.response);
    client.close();
});`

**Comment by veny** [comment]
please see docu:
1) https://github.com/veny/GearmaNode#job-events
2) http://gearman.org/protocol/

WORK_COMPLETE is only for non-background jobs, background jobs are detached.
